### ISSUE TITLE
Meetup #Mar 2017

### ISSUE THREAD

**Issue by indiejoseph** [ml-hongkong/meetup#1]
第一次 Meetup 想大家討論下這個 Group 的方向。

## 日期 Date
- 2017年3月23(星期四) 晚上 7:30

## 地點 Location
- OneSky HQ 鰂魚涌七姊妹道 206-208 號 2 樓 (Quarry Bay MTR Exit C)

## Sharing
- Structure of the mental-state vector @Cybernetic1
- Activation Functions @ywchan2005
- Recurrent Neural Network @indiejoseph

## Papers
- [A Comparative Study of Word Embeddings for Reading Comprehension](https://arxiv.org/pdf/1703.00993.pdf)
- [A Thorough Examination of theCNN/Daily Mail Reading Comprehension Task](https://arxiv.org/pdf/1606.02858.pdf)
- [Gated-Attention Readers for Text Comprehension](https://arxiv.org/pdf/1606.01549.pdf)

## 比D意見
https://gitter.im/ml-hongkong/meetup

**Comment by bencrox** [comment]
http://nlp.stanford.edu/~wcmac/papers/20140716-UNLU.pdf
Not too old

**Comment by indiejoseph** [comment]
今月的 Group Study 都是有關 Reading Comprehension 

選了3份 Papers, 第一份是引用了第二及第三份的 Model 作比較, 配合不同的 Word Embedding methods，大家先看一次，將不明白的地方到 meetup 時討論。

A Comparative Study of Word Embeddings for Reading Comprehension
https://arxiv.org/pdf/1703.00993.pdf

A Thorough Examination of theCNN/Daily Mail Reading Comprehension Task
https://arxiv.org/pdf/1606.02858.pdf

Gated-Attention Readers for Text Comprehension
https://arxiv.org/pdf/1606.01549.pdf

**Comment by Cybernetic1** [comment]
My topic = "structure of the mental-state vector", 讨论如何用 deep reinforcement learning 建构一个最简单的 cognitive architecture。
